name: validate
on: [push]

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.26'

    - name: 🕵️ run linter
      run: make setup lint

    - name: 👮‍♀️ run unit tests
      run: make test/unit

    - name: 🔌 run redis integration tests
      run: make test/redis
